name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install some packages
      run: sudo apt install libunistring-dev libgtk-3-dev libaom-dev libdav1d-dev librust-atk-dev ffmpeg libasound2-dev
    - name: Build
      run: cargo -l libavformat build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
          name: phira-linux
          path: ./target/*phira*
          
